### ISSUE TITLE
Layout defined is not loaded correctly

### ISSUE THREAD

**Issue by espressobytes** [magento-hackathon/layered-landing#11]
Usually in the design section of one Landing Page, you should be able to define a custom page layout that you want to use (e.g. "2 column right" or "3 column, etc.). But when I try to change that, the Landing Page still looks like the same. 
Also, I tried to modify the code, but I cannot find the right spot to define the template which should be used to show the landing page.
Any hint? For example how I can change the landing-page template file within the code?
Thanks in advance!

**Comment by peterjaap** [comment]
This works fine for me. Are you sure there is not another extension or layout handle conflicting with this set up?

**Comment by sandermangel** [comment]
Can not be reproduced
