### ISSUE TITLE
Not working on 1.7

### ISSUE THREAD

**Issue by EvrijnSD** [magento-hackathon/layered-landing#17]
Not working on 1.7 problems with 
a:5:{i:0;s:88:"Invalid method Mage_Catalog_Block_Navigation::addCacheTag(Array
(
    [0] => TOPMENU
)
)";i:1;s:2033:"#0 [internal function]: Varien_Object->__call('addCacheTag', Array)

**Comment by Schrank** [comment]
right, this method doesn't exist in 1.7 but you can fake it and do everything by hand instead of this method call:

    public function addCacheTag($tag)
    {
        $tag = is_array($tag) ? $tag : array($tag);
        $tags = !$this->hasData(self::CACHE_TAGS_DATA_KEY) ?
            $tag : array_merge($this->getData(self::CACHE_TAGS_DATA_KEY), $tag);
        $this->setData(self::CACHE_TAGS_DATA_KEY, $tags);
        return $this;
    }
