### ISSUE TITLE
Invalid method Mage_Catalog_Block_Navigation::canShowBlock

### ISSUE THREAD

**Issue by thomas-harding** [magento-hackathon/layered-landing#20]
Just installed the extension on a site that's barely been modified (1.9). I set up a landing page for one of my categories and I'm getting the following error when I visit it:

`a:5:{i:0;s:70:"Invalid method Mage_Catalog_Block_Navigation::canShowBlock(Array
(
)
)";i:1;s:3010:"#0 C:\xampp\htdocs\----l\app\design\frontend\fat\default\template\layeredlanding\catalog\layer\view.phtml(34): Varien_Object->__call('canShowBlock', Array)
#1 C:\xampp\htdocs\----\app\design\frontend\fat\default\template\layeredlanding\catalog\layer\view.phtml(34): Mage_Catalog_Block_Navigation->canShowBlock()`

**Comment by sandermangel** [comment]
Hi Thomas, 
this is because the category you're using the layered landing on is not a layered navigation category. The catalog.leftnav block has to be of the type "catalog/layer_view".

Can you call the category in the frontend and make sure it's layered navigation? (Is anchor on etc)

**Comment by sandermangel** [comment]
Closed due to lack of information

**Comment by ashvinim0003** [comment]
I was getting the same error on the frontend. I have fixed it by changing is anchor to Yes for category from the backend.
You can find is_anchor settings under the display mode on the category page.
