### ISSUE TITLE
Custom Attribute Set

### ISSUE THREAD

**Issue by aziwaan** [magento-hackathon/layered-landing#22]
Does layered-landing support custom attribute sets?

Great idea for extension by the way.

Edit:  After installing with Modman I cant see the section in admin where you specify the attributes?
![screen shot 2015-10-27 at 2 31 19 pm](https://cloud.githubusercontent.com/assets/8869016/10749569/70c3606e-7cb7-11e5-9e59-0dd9bf273831.png)

**Comment by sandermangel** [comment]
Hi Aziwaan, 
"Does layered-landing support custom attribute sets?" 
- what do you mean by that? Could you elaborate? 

"After installing with Modman I cant see the section in admin where you specify the attributes?"
- I wasn't able to reproduce this. Could you check the symlink to the phtml files for the adminhtml are made correctly? Some debugging info would be very helpfull

**Comment by sandermangel** [comment]
Closed due to no feedback
