### ISSUE TITLE
Attributes only shows Color and Price

### ISSUE THREAD

**Issue by neilbradley** [magento-hackathon/layered-landing#23]
Hi,
Just wondering how to get other attributes to appear when creating a page? I'm trying to get 'New From' to appear but it does not display. I'd like to create a page that shows New products with the layered navigation (instead of creating a category as this screws up Google Analytics).

Is it because this field can't be used in layered navigation?

**Comment by sandermangel** [comment]
Hi Neil, the fields depend on layered navigation so indeed, only works with fields also allowed in layered navigation
