### ISSUE TITLE
Errors while saving and 404 in frontend

### ISSUE THREAD

**Issue by kkoepke** [magento-hackathon/layered-landing#26]
After saving a landing page i have some errors in system.log. In frontend the page appears in the navigation but gives an 404. Any ideas?

`2017-06-08T12:52:42+00:00 ERR (admin): /index.php/admin/layeredlanding/edit/id/5/key/0e6b3314c4d99ebf32ac0adbb9ad93c6/ 
REQUEST: -
TIME: 2.064183s
ADDRESS: 127.0.0.1
USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
FILE: app/code/core/Mage/Core/functions.php:247
Warning: Declaration of Hackathon_Layeredlanding_Model_Options_Boolean::toOptionArray() should be compatible with Mage_Page_Model_Source_Layout::toOptionArray($withEmpty = false)  in app/code/community/Hackathon/Layeredlanding/Model/Options/Boolean.php on line 3
2017-06-08T12:52:42+00:00 ERR (admin): /index.php/admin/layeredlanding/edit/id/5/key/0e6b3314c4d99ebf32ac0adbb9ad93c6/ 
REQUEST: -
TIME: 2.066917s
ADDRESS: 127.0.0.1
USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
FILE: app/code/core/Mage/Core/functions.php:247
Warning: Declaration of Hackathon_Layeredlanding_Model_Options_Layout::toOptionArray() should be compatible with Mage_Page_Model_Source_Layout::toOptionArray($withEmpty = false)  in app/code/community/Hackathon/Layeredlanding/Model/Options/Layout.php on line 14
2017-06-08T12:52:48+00:00 ERR (admin): /index.php/admin/layeredlanding/edit/id/5/key/0e6b3314c4d99ebf32ac0adbb9ad93c6/ 
REQUEST: -
TIME: 1.941388s
ADDRESS: 127.0.0.1
USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
FILE: app/code/core/Mage/Core/functions.php:247
Warning: Declaration of Hackathon_Layeredlanding_Model_Options_Boolean::toOptionArray() should be compatible with Mage_Page_Model_Source_Layout::toOptionArray($withEmpty = false)  app/code/community/Hackathon/Layeredlanding/Model/Options/Boolean.php on line 3
2017-06-08T12:52:48+00:00 ERR (admin): /index.php/admin/layeredlanding/edit/id/5/key/0e6b3314c4d99ebf32ac0adbb9ad93c6/ 
REQUEST: -
TIME: 1.943603s
ADDRESS: 127.0.0.1
USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
FILE: app/code/core/Mage/Core/functions.php:247
Warning: Declaration of Hackathon_Layeredlanding_Model_Options_Layout::toOptionArray() should be compatible with Mage_Page_Model_Source_Layout::toOptionArray($withEmpty = false)  in app/code/community/Hackathon/Layeredlanding/Model/Options/Layout.php on line 14`

**Comment by sprankhub** [comment]
Let me guess... You use PHP7? :-)

I just proposed PR #27 to fix this issue.
