### ISSUE TITLE
Add images upload

### ISSUE THREAD

**Issue by BWunderlich** [magento-hackathon/layered-landing#9]
I would love to be able to upload at least one image to be used on the landing page for an emotional impression or a manufacturer logo.

**Comment by peterjaap** [comment]
Might be adding this this week.

@tegansnyder's suggestion is correct, but too cumbersome for my clients.

**Comment by peterjaap** [comment]
I've added this to the extension and issued a pull request; https://github.com/magento-hackathon/layered-landing/pull/12

**Comment by peterjaap** [comment]
And merged!
